const numberButtons = document.querySelectorAll('[data-number]')
const operationButtons = document.querySelectorAll('[data-operation]')
const equalsButton = document.querySelectorAll ('[data-equals]')
const deleteButton = document.querySelectorAll ('[data-equals]')
const allClearButton = document.querySelectorAll ('[data-equals]')
const perviousOperandTextElement = document.querySelectorAll ('[data-equals]')
const currentOperandTextElement = document.querySelectorAll ('[data-equals]')